; --- Encabezado y Directivas (MASM 32-bit) ---
.386
option casemap:none
includelib \masm32\lib\kernel32.lib
include \masm32\include\masm32rt.inc
printf PROTO C : VARARG

; Las rutinas de impresión se manejarán con invoke printf de masm32rt.inc

.DATA
; Variables Auxiliares (DD ?) y Constantes

; Formatos de printf para rutinas de I/O
_FMT_INT	DB "%d", 0
_FMT_FLOAT	DB "%.10f", 0
_FMT_STRING	DB "%s", 0
_A_PROGRAMAVALIDO	DD ?
_B_PROGRAMAVALIDO	DD ?
_C_PROGRAMAVALIDO	DD ?
_CTE_1I	DD 1
_CTE_2I	DD 2
_@T1_PROGRAMAVALIDO	DD ?
_CTE_HOLA	DB "HOLA", 0
_CTE_divis___dsad_p3rÖ	DB "divis,,.dsad p3rÖ", 0
_CTE_B_ES_MENOR	DB "B ES MENOR", 0
_CTE_1	DD 1
_SALTO_LINEA	DB 0Dh, 0Ah, 0

; Rutinas de error de Runtime
_ERR_CAPTION	DB "Error de Ejecucion", 0
_DIV_CERO	DB "Error en runtime: Division por cero!", 0
_OVERFLOW_FLOAT	DB "Error en runtime: Overflow de flotante!", 0
_RECURSION_ERR	DB "Error en runtime: Recursion directa prohibida!", 0

.CODE
; Rutina de error para división por cero
_RTH_DIV_CERO:
	INVOKE MessageBox, NULL, ADDR _DIV_CERO, ADDR _ERR_CAPTION, MB_OK + MB_ICONSTOP
	JMP _EXIT_PROGRAM
; Rutina de error para Overflow de flotante
_RTH_OVERFLOW_FLOAT:
	INVOKE MessageBox, NULL, ADDR _OVERFLOW_FLOAT, ADDR _ERR_CAPTION, MB_OK + MB_ICONSTOP
	JMP _EXIT_PROGRAM
; Rutina de error para recursión directa
_RTH_RECURSION_DIRECTA:
	INVOKE MessageBox, NULL, ADDR _RECURSION_ERR, ADDR _ERR_CAPTION, MB_OK + MB_ICONSTOP
	JMP _EXIT_PROGRAM

start:
	FINIT
	CALL _PROGRAMAVALIDO_PROGRAMAVALIDO
_EXIT_PROGRAM:
	INVOKE ExitProcess, 0

_PROGRAMAVALIDO_PROGRAMAVALIDO PROC
	PUSH EBP
	MOV EBP, ESP

	; --- Traduccion Polaca Inversa (PROGRAMAVALIDO:PROGRAMAVALIDO) ---
L_1:
	; OPERANDO OMITIDO
L_2:
	; OPERANDO OMITIDO
L_3:
	MOV EAX, _CTE_1I
	MOV _A_PROGRAMAVALIDO, EAX
L_4:
	; OPERANDO OMITIDO
L_5:
	PUSH _A_PROGRAMAVALIDO
	PUSH OFFSET _FMT_INT
	CALL printf
	ADD ESP, 8

	; Salto de linea forzado
	PUSH OFFSET _SALTO_LINEA
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8
L_6:
	; OPERANDO OMITIDO
L_7:
	; OPERANDO OMITIDO
L_8:
	MOV EAX, _CTE_2I
	MOV _B_PROGRAMAVALIDO, EAX
L_9:
	; OPERANDO OMITIDO
L_10:
	; OPERANDO OMITIDO
L_11:
	MOV EAX, _A_PROGRAMAVALIDO
	ADD EAX, _B_PROGRAMAVALIDO
	MOV _@T1_PROGRAMAVALIDO, EAX
L_12:
	; OPERANDO OMITIDO
L_13:
	; ASIGNACION REDUNDANTE OMITIDA (Operando no es SymbolEntry)
L_14:
	; OPERANDO OMITIDO
L_15:
	; OPERANDO OMITIDO
L_16:
	MOV EAX, _@T1_PROGRAMAVALIDO
	MOV _A_PROGRAMAVALIDO, EAX
L_17:
	; OPERANDO OMITIDO
L_18:
	; OPERANDO OMITIDO
L_19:
	MOV EAX, OFFSET _CTE_HOLA
	MOV _C_PROGRAMAVALIDO, EAX
L_20:
	; OPERANDO OMITIDO
L_21:
	PUSH OFFSET _CTE_divis___dsad_p3rÖ
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8

	; Salto de linea forzado
	PUSH OFFSET _SALTO_LINEA
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8
L_22:
	; OPERANDO OMITIDO
L_23:
	PUSH OFFSET _CTE_B_ES_MENOR
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8

	; Salto de linea forzado
	PUSH OFFSET _SALTO_LINEA
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8
L_24:
	; OPERANDO OMITIDO
L_25:
	PUSH _C_PROGRAMAVALIDO
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8

	; Salto de linea forzado
	PUSH OFFSET _SALTO_LINEA
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8
L_26:
	; OPERANDO OMITIDO
L_27:
	PUSH _A_PROGRAMAVALIDO
	PUSH OFFSET _FMT_INT
	CALL printf
	ADD ESP, 8

	; Salto de linea forzado
	PUSH OFFSET _SALTO_LINEA
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8

	; --- Fin Traduccion Polaca Inversa ---
_PROGRAMAVALIDO_PROGRAMAVALIDO_EPILOGUE:
	MOV ESP, EBP
	POP EBP
	RET
_PROGRAMAVALIDO_PROGRAMAVALIDO ENDP
END start
