; --- Encabezado y Directivas (MASM 32-bit) ---
.386
option casemap:none
includelib \masm32\lib\kernel32.lib
include \masm32\include\masm32rt.inc
printf PROTO C : VARARG

; Las rutinas de impresión se manejarán con invoke printf de masm32rt.inc

.DATA
; Variables Auxiliares (DD ?) y Constantes

; Formatos de printf para rutinas de I/O
_FMT_INT	DB "%d", 0
_FMT_FLOAT	DB "%.10f", 0
_FMT_STRING	DB "%s", 0
_FRECURSIVA_PROGRAMARUNTIMECHECK	DD ? ; (uso=funcion tipo=null)
_X_PROGRAMARUNTIMECHECK_FRECURSIVA	DD ?
_A_PROGRAMARUNTIMECHECK_FRECURSIVA	DD ?
_CTE_3_5	DD 3.5
_@T1_PROGRAMARUNTIMECHECK_FRECURSIVA	DD ?
_DIVISOR_PROGRAMARUNTIMECHECK	DD ?
_RESULTADO_PROGRAMARUNTIMECHECK	DD ?
_MAXVAL_PROGRAMARUNTIMECHECK	DD ?
_RESULTADOFLOAT_PROGRAMARUNTIMECHECK	DD ?
_CTE_0I	DD 0
_CTE_10I	DD 10
_@T2_PROGRAMARUNTIMECHECK	DD ?
_CTE_ESTO_NO_DEBE_IMPRIMIRSE__Fallo_en_división_por_cero___INT_	DB "ESTO NO DEBE IMPRIMIRSE (Fallo en división por cero - INT)", 0
_@T3_PROGRAMARUNTIMECHECK	DD ?
_CTE_ESTO_TAMPOCO_DEBE_IMPRIMIRSE__Fallo_en_división_por_cero___FLOAT_	DB "ESTO TAMPOCO DEBE IMPRIMIRSE (Fallo en división por cero - FLOAT)", 0
_CTE_3_40282347F_38	DD 3.40282347E+38
_CTE_10_0F_0	DD 10.0E+0
_@T4_PROGRAMARUNTIMECHECK	DD ?
_CTE_ESTO_TAMPOCO_DEBE_IMPRIMIRSE__Fallo_en_Overflow_	DB "ESTO TAMPOCO DEBE IMPRIMIRSE (Fallo en Overflow)", 0
_@T5_PROGRAMARUNTIMECHECK	DD ?
_CTE_FIN_PRUEBAS_DE_FALLO	DB "FIN PRUEBAS DE FALLO", 0
_CTE_1	DD 1
_SALTO_LINEA	DB 0Dh, 0Ah, 0

; Rutinas de error de Runtime
_ERR_CAPTION	DB "Error de Ejecucion", 0
_DIV_CERO	DB "Error en runtime: Division por cero!", 0
_OVERFLOW_FLOAT	DB "Error en runtime: Overflow de flotante!", 0
_RECURSION_ERR	DB "Error en runtime: Recursion directa prohibida!", 0

.CODE
; Rutina de error para división por cero
_RTH_DIV_CERO:
	INVOKE MessageBox, NULL, ADDR _DIV_CERO, ADDR _ERR_CAPTION, MB_OK + MB_ICONSTOP
	JMP _EXIT_PROGRAM
; Rutina de error para Overflow de flotante
_RTH_OVERFLOW_FLOAT:
	INVOKE MessageBox, NULL, ADDR _OVERFLOW_FLOAT, ADDR _ERR_CAPTION, MB_OK + MB_ICONSTOP
	JMP _EXIT_PROGRAM
; Rutina de error para recursión directa
_RTH_RECURSION_DIRECTA:
	INVOKE MessageBox, NULL, ADDR _RECURSION_ERR, ADDR _ERR_CAPTION, MB_OK + MB_ICONSTOP
	JMP _EXIT_PROGRAM

_FRECURSIVA_PROGRAMARUNTIMECHECK PROC
	PUSH EBP
	MOV EBP, ESP

	; --- Traduccion Polaca Inversa (FRECURSIVA:PROGRAMARUNTIMECHECK) --- 
L_1:
	; ERROR: Instruccion 'PROC_FRECURSIVA:PROGRAMARUNTIMECHECK' no implementada.
L_2:
	; OPERANDO OMITIDO
L_3:
	; OPERANDO OMITIDO
L_4:
	FLD DWORD PTR _CTE_3_5
	FSTP DWORD PTR _A_PROGRAMARUNTIMECHECK_FRECURSIVA
L_5:
	; OPERANDO OMITIDO
L_6:
	; OPERANDO OMITIDO
L_7:
	FLD DWORD PTR _A_PROGRAMARUNTIMECHECK_FRECURSIVA
	FSTP DWORD PTR _X_PROGRAMARUNTIMECHECK_FRECURSIVA
L_8:
	; OPERANDO OMITIDO
L_9:
	JMP _RTH_RECURSION_DIRECTA
L_10:
	; OPERANDO OMITIDO
L_11:
	; ASIGNACION REDUNDANTE OMITIDA (Operando no es SymbolEntry)
L_12:
	; OPERANDO OMITIDO
L_13:
	; OPERANDO OMITIDO
L_14:
	FLD DWORD PTR _X_PROGRAMARUNTIMECHECK_FRECURSIVA
	FSTP DWORD PTR _A_PROGRAMARUNTIMECHECK_FRECURSIVA
L_15:
	JMP _FRECURSIVA_PROGRAMARUNTIMECHECK_EPILOGUE
L_16:
	; ERROR: Instruccion 'ENDP_FRECURSIVA:PROGRAMARUNTIMECHECK' no implementada.

	; --- Fin Traduccion Polaca Inversa --- 
_FRECURSIVA_PROGRAMARUNTIMECHECK_EPILOGUE:
	MOV ESP, EBP
	POP EBP
	RET
_FRECURSIVA_PROGRAMARUNTIMECHECK ENDP

start:
	CALL _PROGRAMARUNTIMECHECK_PROGRAMARUNTIMECHECK
_EXIT_PROGRAM:
	INVOKE ExitProcess, 0

_PROGRAMARUNTIMECHECK_PROGRAMARUNTIMECHECK PROC
	PUSH EBP
	MOV EBP, ESP

	; --- Traduccion Polaca Inversa (PROGRAMARUNTIMECHECK:PROGRAMARUNTIMECHECK) --- 
L_1:
	; OPERANDO OMITIDO
L_2:
	; OPERANDO OMITIDO
L_3:
	MOV EAX, _CTE_0I
	MOV _DIVISOR_PROGRAMARUNTIMECHECK, EAX
L_4:
	; OPERANDO OMITIDO
L_5:
	; OPERANDO OMITIDO
L_6:
	; Chequeo de division por cero (INT)
	MOV EBX, _DIVISOR_PROGRAMARUNTIMECHECK
	CMP EBX, 0
	JE _RTH_DIV_CERO
	MOV EAX, _CTE_10I
	CDQ
	IDIV EBX
	MOV _@T2_PROGRAMARUNTIMECHECK, EAX
L_7:
	; OPERANDO OMITIDO
L_8:
	; ASIGNACION REDUNDANTE OMITIDA (Operando no es SymbolEntry)
L_9:
	; OPERANDO OMITIDO
L_10:
	; OPERANDO OMITIDO
L_11:
	MOV EAX, _@T2_PROGRAMARUNTIMECHECK
	MOV _RESULTADO_PROGRAMARUNTIMECHECK, EAX
L_12:
	; OPERANDO OMITIDO
L_13:
	PUSH OFFSET _CTE_ESTO_NO_DEBE_IMPRIMIRSE__Fallo_en_división_por_cero___INT_
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8

	; Salto de linea forzado
	PUSH OFFSET _SALTO_LINEA
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8
L_14:
	; OPERANDO OMITIDO
L_15:
	; OPERANDO OMITIDO
L_16:
	; Chequeo de division por cero (INT)
	MOV EBX, _DIVISOR_PROGRAMARUNTIMECHECK
	CMP EBX, 0
	JE _RTH_DIV_CERO
	MOV EAX, _CTE_10I
	CDQ
	IDIV EBX
	MOV _@T3_PROGRAMARUNTIMECHECK, EAX
L_17:
	; OPERANDO OMITIDO
L_18:
	; ASIGNACION REDUNDANTE OMITIDA (Operando no es SymbolEntry)
L_19:
	; OPERANDO OMITIDO
L_20:
	; OPERANDO OMITIDO
L_21:
	MOV EAX, _@T3_PROGRAMARUNTIMECHECK
	MOV _RESULTADO_PROGRAMARUNTIMECHECK, EAX
L_22:
	; OPERANDO OMITIDO
L_23:
	PUSH OFFSET _CTE_ESTO_TAMPOCO_DEBE_IMPRIMIRSE__Fallo_en_división_por_cero___FLOAT_
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8

	; Salto de linea forzado
	PUSH OFFSET _SALTO_LINEA
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8
L_24:
	; OPERANDO OMITIDO
L_25:
	; OPERANDO OMITIDO
L_26:
	FLD DWORD PTR _CTE_3_40282347F_38
	FSTP DWORD PTR _MAXVAL_PROGRAMARUNTIMECHECK
L_27:
	; OPERANDO OMITIDO
L_28:
	; OPERANDO OMITIDO
L_29:
	FLD DWORD PTR _MAXVAL_PROGRAMARUNTIMECHECK
	FLD DWORD PTR _CTE_10_0F_0
	FMUL
	; Chequeo de Overflow/Underflow Flotante
	FWAIT
	FNSTSW AX
	TEST AH, 0004h
	JNE _RTH_OVERFLOW_FLOAT
	FSTP DWORD PTR _@T4_PROGRAMARUNTIMECHECK
L_30:
	; OPERANDO OMITIDO
L_31:
	; ASIGNACION REDUNDANTE OMITIDA (Operando no es SymbolEntry)
L_32:
	; OPERANDO OMITIDO
L_33:
	; OPERANDO OMITIDO
L_34:
	FLD DWORD PTR _@T4_PROGRAMARUNTIMECHECK
	FSTP DWORD PTR _RESULTADOFLOAT_PROGRAMARUNTIMECHECK
L_35:
	; OPERANDO OMITIDO
L_36:
	PUSH OFFSET _CTE_ESTO_TAMPOCO_DEBE_IMPRIMIRSE__Fallo_en_Overflow_
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8

	; Salto de linea forzado
	PUSH OFFSET _SALTO_LINEA
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8
L_37:
	; OPERANDO OMITIDO
L_38:
	; OPERANDO OMITIDO
L_39:
	FLD DWORD PTR _MAXVAL_PROGRAMARUNTIMECHECK
	FSTP DWORD PTR _X_PROGRAMARUNTIMECHECK_FRECURSIVA
L_40:
	; OPERANDO OMITIDO
L_41:
	CALL _FRECURSIVA_PROGRAMARUNTIMECHECK
L_42:
	; OPERANDO OMITIDO
L_43:
	; ASIGNACION REDUNDANTE OMITIDA (Operando no es SymbolEntry)
L_44:
	; OPERANDO OMITIDO
L_45:
	; OPERANDO OMITIDO
L_46:
	FLD DWORD PTR _X_PROGRAMARUNTIMECHECK_FRECURSIVA
	FSTP DWORD PTR _MAXVAL_PROGRAMARUNTIMECHECK
L_47:
	; OPERANDO OMITIDO
L_48:
	; OPERANDO OMITIDO
L_49:
	FLD DWORD PTR _@T5_PROGRAMARUNTIMECHECK
	FSTP DWORD PTR _RESULTADOFLOAT_PROGRAMARUNTIMECHECK
L_50:
	; OPERANDO OMITIDO
L_51:
	PUSH OFFSET _CTE_FIN_PRUEBAS_DE_FALLO
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8

	; Salto de linea forzado
	PUSH OFFSET _SALTO_LINEA
	PUSH OFFSET _FMT_STRING
	CALL printf
	ADD ESP, 8

	; --- Fin Traduccion Polaca Inversa --- 
_PROGRAMARUNTIMECHECK_PROGRAMARUNTIMECHECK_EPILOGUE:
	MOV ESP, EBP
	POP EBP
	RET
_PROGRAMARUNTIMECHECK_PROGRAMARUNTIMECHECK ENDP
END start
